-- 코드를 입력하세요
SELECT
    A.ANIMAL_ID,
    A.NAME
FROM
    (
    SELECT 
        AI.ANIMAL_ID,
        AI.NAME,
        DATEDIFF(AO.DATETIME, AI.DATETIME) AS DATE
    FROM 
        ANIMAL_INS AI LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
    ) AS A
ORDER BY A.DATE DESC
LIMIT 2